name: Rust

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and Tests
      env:
        AMARI_TOKEN: ${{ secrets.AMARI_TOKEN }}
      run: |
        cargo build --release --verbose
        cargo test --release --verbose